

/* AHORA VEREMOS COMO ACTUAR JAVASCRIPT EN EL DOM, COMO SELECCIONAR ELEMENTOS DEL HTML, 
COMO CREAR EVENTOS, MODIFICAR HTML ETC

LA INTERACCIÓN

COMO SELECCIONAR CODIGO HTML, 3 FORMAS

    QUERYSELECTOR
    QUERYSELECTORALL
    GETELEMENTBYID

    TODOS INICIAN CON DOCUMENT*/


    /* QUERYSELECTOR ******************************

    RETORNA UNO O NINGUN ELEMENTO
    MUY SIMILARES A LOS QUE TENEMOS EN CSS 
        CLASES CON .
        ID CON #

    DOCUMENT HACE REFERENCIA A TODO EL DOCUMENTO HTML*/

   /* EJERICIO

    CREAR UNA SECCIÓN, CON UN H1, UNA IMAGEN DE FONDO, UN BOTÓN Y 
    UN DIV CON TRES ENLACES CON CLASE enlace Y EL DIV CON LA CLASE navPrincipal
    DARLE A LA SECCIÓN LA CLASE seccionPrincipal
    DARLE AL BOTÓN UN ID botonPrincipal*/


    

